### ISSUE TITLE
Change from PDF to markdown

### ISSUE THREAD

**Issue by AJAYK-01** [anushka23g/Complete-Placement-Preparation#8]
Github's preview for PDF is quite slow and the hyperlinks you have given inside the pdfs don't seem to be clickable while in github.

Only downloading the PDF gets the hyperlinks. But since the documents are in a relatively quite simple format I think it would be great if it was converted to Markdown files as it would render fast previews in Github as well as give access to the links within Github itself without having to download the file.

**Comment by anjannair** [comment]
Update - @AJAYK-01 you can check out the PR and let me know if this is what was expected

**Comment by AJAYK-01** [comment]
> Update - @AJAYK-01 you can check out the PR and let me know if this is what was expected

Yeap!
